import { Candidate, EmployerRequest, NotificationItem } from "./types";

export const initialEmployerRequests: EmployerRequest[] = [
  {
    id: "EMP-2026-001",
    companyName: "سماء الرياض للحلول الرقمية (Sama Digital)",
    industry: "technology",
    contactPerson: "م. خالد السبيعي (CTO)",
    email: "recruitment@samadigital.sa",
    phone: "+966 50 491 8822",
    website: "https://samadigital.sa",
    linkedin: "https://linkedin.com/company/samadigital",
    city: "الرياض",
    country: "المملكة العربية السعودية",
    jobTitle: "Lead Cloud Solutions Architect",
    jobType: "full-time",
    experienceLevel: "lead",
    minSalary: 32000,
    maxSalary: 42000,
    currency: "SAR",
    numberOfOpenings: 2,
    jobDescription: "نبحث عن مهندس حلول سحابية أول لقيادة التحول الرقمي لمنصات البنية التحتية بالاعتماد على AWS/Kubernetes مع تطبيق معايير الأمان السحابي وحوكمة البيانات لقطاع البنوك.",
    requiredSkills: ["AWS", "Kubernetes", "Terraform", "Microservices", "DevOps", "Cybersecurity", "Python"],
    qualifications: "خبرة لا تقل عن 8 سنوات في تصميم البنى التحتية السحابية الواسعة وشهادات معتمدة AWS Solution Architect Professional.",
    status: "shortlisting",
    urgency: "urgent",
    submittedAt: "2026-08-14T09:30:00.000Z",
    updatedAt: "2026-08-15T14:20:00.000Z",
    assignedCandidateIds: ["CAND-101", "CAND-107"],
    notes: "تم تجهيز قائمة مبدئية وإرسالها للـ CTO للمراجعة الفنية.",
    fileName: "JD_Cloud_Architect_SamaDigital.pdf",
    fileSize: "2.4 MB",
  },
  {
    id: "EMP-2026-002",
    companyName: "مجموعة الرواد المالية (Al-Rowad Capital)",
    industry: "finance_banking",
    contactPerson: "أ. نورة المنصور (Head of People)",
    email: "talent@alrowadcapital.com",
    phone: "+966 55 123 9988",
    website: "https://alrowadcapital.com",
    city: "الرياض",
    country: "المملكة العربية السعودية",
    jobTitle: "Head of Risk & Compliance",
    jobType: "full-time",
    experienceLevel: "executive",
    minSalary: 45000,
    maxSalary: 60000,
    currency: "SAR",
    numberOfOpenings: 1,
    jobDescription: "قيادة إدارة الامتثال والمخاطر وفق لوائح البنك المركزي السعودي (SAMA) وهيئة السوق المالية (CMA) والإشراف على التدقيق المالي ومكافحة غسيل الأموال.",
    requiredSkills: ["SAMA Regulations", "Risk Management", "CMA Compliance", "AML", "Financial Audit", "Corporate Governance"],
    qualifications: "خبرة مصرفية واستثمارية لا تقل عن 10 سنوات، شهادات مهنية مثل CAMS أو FRM.",
    status: "in_progress",
    urgency: "high",
    submittedAt: "2026-08-12T11:15:00.000Z",
    updatedAt: "2026-08-14T16:00:00.000Z",
    assignedCandidateIds: ["CAND-104"],
    notes: "مرشح تنفيذي واعد تم تحديد موعد مقابلة معه الأسبوع القادم.",
    fileName: "JD_Head_of_Risk.pdf",
    fileSize: "1.8 MB",
  },
  {
    id: "EMP-2026-003",
    companyName: "نيوم للطاقة المتجددة (NEOM Energy)",
    industry: "engineering",
    contactPerson: "د. طارق العمراني",
    email: "careers@neom-energy.sa",
    phone: "+966 54 887 6655",
    website: "https://neom.com",
    city: "نيوم / تبوك",
    country: "المملكة العربية السعودية",
    jobTitle: "Senior Solar & Grid Integration Engineer",
    jobType: "full-time",
    experienceLevel: "senior",
    minSalary: 28000,
    maxSalary: 38000,
    currency: "SAR",
    numberOfOpenings: 3,
    jobDescription: "إدارة وتصميم شبكات الربط الكهربائي لمحطات الطاقة الشمسية الكهروضوئية وتكاملها مع شبكات الجهد الفائق ومحطات التخزين بالبطاريات BESS.",
    requiredSkills: ["Solar PV", "Grid Integration", "BESS", "AutoCAD Electrical", "Power Systems Analysis", "Project Management"],
    qualifications: "بكالوريوس هندسة قوى كهربائية وخبرة 6+ سنوات في مشاريع الطاقة المتجددة الكبرى.",
    status: "new",
    urgency: "normal",
    submittedAt: "2026-08-15T08:00:00.000Z",
    updatedAt: "2026-08-15T08:00:00.000Z",
    assignedCandidateIds: [],
    notes: "طلب وارد حديثاً من بوابة الموقع، بانتظار الفرز المبدئي.",
    fileName: "NEOM_Grid_Specs.docx",
    fileSize: "3.1 MB",
  },
  {
    id: "EMP-2026-004",
    companyName: "هيلث كير الخليج الدولية (Gulf Health Group)",
    industry: "healthcare",
    contactPerson: "د. فاطمة الزهراني",
    email: "hr@gulfhealthgroup.org",
    phone: "+971 4 888 1234",
    website: "https://gulfhealthgroup.org",
    city: "دبي / الرياض",
    country: "الإمارات / السعودية",
    jobTitle: "Medical Operations Director",
    jobType: "full-time",
    experienceLevel: "executive",
    minSalary: 50000,
    maxSalary: 70000,
    currency: "SAR",
    numberOfOpenings: 1,
    jobDescription: "الإشراف التشغيلي على سلسلة مستشفيات ومراكز جراحة اليوم الواحد وضمان تطبيق معايير JCI والاعتماد الصحي الدولي وإدارة الكوادر الطبية والتمريضية.",
    requiredSkills: ["Hospital Administration", "JCI Standards", "Healthcare Quality", "Clinical Operations", "Budgeting", "Leadership"],
    qualifications: "ماجستير إدارة مستشفيات أو دكتوراه في الطب مع خبرة قيادية لا تقل عن 12 سنة.",
    status: "interviewing",
    urgency: "urgent",
    submittedAt: "2026-08-08T10:00:00.000Z",
    updatedAt: "2026-08-13T12:00:00.000Z",
    assignedCandidateIds: ["CAND-105"],
    notes: "المرشح اجتاز المقابلة الأولى مع مجلس الإدارة.",
    fileName: "Medical_Director_Scope.pdf",
    fileSize: "1.5 MB",
  },
  {
    id: "EMP-2026-005",
    companyName: "منصة نون للنمو والتجارة (Noon Scale Lab)",
    industry: "marketing_sales",
    contactPerson: "أ. باسل التميمي (Growth Lead)",
    email: "hiring@noonscalelab.com",
    phone: "+966 56 333 4411",
    website: "https://noonscalelab.com",
    city: "جدة",
    country: "المملكة العربية السعودية",
    jobTitle: "Senior Performance Marketing & SEO Lead",
    jobType: "remote",
    experienceLevel: "senior",
    minSalary: 22000,
    maxSalary: 30000,
    currency: "SAR",
    numberOfOpenings: 1,
    jobDescription: "قيادة حملات الاستحواذ الرقمي المدفوعة (Google, Meta, TikTok, Snapchat) وتحسين محركات البحث SEO لمنصات تجارة إلكترونية تحقق أكثر من 100 مليون ريال سنوياً.",
    requiredSkills: ["Performance Marketing", "SEO Strategy", "Google Ads", "TikTok Ads", "GA4", "CRO", "Data Analytics"],
    qualifications: "خبرة لا تقل عن 5 سنوات في التجارة الإلكترونية وسجل مثبت في تحسين ROAS وتخفيض CAC.",
    status: "completed",
    urgency: "high",
    submittedAt: "2026-07-28T14:30:00.000Z",
    updatedAt: "2026-08-10T11:00:00.000Z",
    assignedCandidateIds: ["CAND-102"],
    notes: "تم توظيف المرشح واستلامه العمل بنجاح مع تقييم عميل 5/5.",
    fileName: "JD_Marketing_Lead.pdf",
    fileSize: "980 KB",
  },
  {
    id: "EMP-2026-006",
    companyName: "اللوجستية المتطورة للنقل (FastLogistics KSA)",
    industry: "operations_logistics",
    contactPerson: "أ. عبدالعزيز الدوسري",
    email: "hr@fastlogistics.sa",
    phone: "+966 53 999 7722",
    city: "الدمام",
    country: "المملكة العربية السعودية",
    jobTitle: "Supply Chain & Fleet Optimization Manager",
    jobType: "full-time",
    experienceLevel: "mid",
    minSalary: 18000,
    maxSalary: 25000,
    currency: "SAR",
    numberOfOpenings: 2,
    jobDescription: "إدارة أسطول النقل اللوجستي والمستودعات المركزية وتحسين مسارات التوزيع وتطبيق أنظمة تتبع TMS و WMS الذكية لتقليل زمن التسليم.",
    requiredSkills: ["Supply Chain", "TMS", "WMS", "Fleet Management", "Inventory Control", "KPI Dashboarding"],
    qualifications: "خبرة 4-7 سنوات في إدارة العمليات اللوجستية والنقل السريع.",
    status: "in_progress",
    urgency: "normal",
    submittedAt: "2026-08-11T13:00:00.000Z",
    updatedAt: "2026-08-14T09:15:00.000Z",
    assignedCandidateIds: ["CAND-106"],
    notes: "تم فحص 3 مرشحين وجاري إعداد قائمة المقابلات.",
    fileName: "Fleet_Manager_JD.pdf",
    fileSize: "1.2 MB",
  }
];

export const initialCandidates: Candidate[] = [
  {
    id: "CAND-101",
    fullName: "م. محمد عبدالله القحطاني",
    email: "m.alqahtani.cloud@gmail.com",
    phone: "+966 50 912 3456",
    city: "الرياض",
    country: "المملكة العربية السعودية",
    category: "technology",
    currentTitle: "Senior Cloud & DevOps Architect",
    targetTitle: "Lead Cloud Solutions Architect / Head of Infrastructure",
    yearsOfExperience: 9,
    experienceLevel: "lead",
    education: "بكالوريوس هندسة حاسب - جامعة الملك فهد للبترول والمعادن (KFUPM)",
    currentCompany: "الشركة المتقدمة للحوسبة السحابية",
    noticePeriod: "1_month",
    expectedSalary: 38000,
    currentSalary: 30000,
    currency: "SAR",
    skills: ["AWS", "Kubernetes", "Terraform", "Microservices", "DevOps", "Cybersecurity", "Python", "CI/CD", "Docker", "Linux"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (طلاقة احترافية)"],
    summary: "مهندس بنية تحتية وحوسبة سحابية بخبرة 9 سنوات في تصميم ونشر حلول سحابية معقدة وموثوقة على AWS و Azure لقطاعات البنوك والاتصالات. حاصل على شهادات AWS Solutions Architect Professional و CKA.",
    resumeFileName: "CV_Mohamed_AlQahtani_Cloud.pdf",
    resumeFileSize: "1.4 MB",
    portfolioUrl: "https://qahtani-cloud.dev",
    linkedinUrl: "https://linkedin.com/in/mohamed-alqahtani-cloud",
    githubUrl: "https://github.com/m-qahtani",
    status: "shortlisted",
    rating: 5,
    submittedAt: "2026-08-10T14:20:00.000Z",
    updatedAt: "2026-08-15T11:00:00.000Z",
    hrNotes: "مرشح استثنائي جداً، أجرى اختباراً تقنياً مع فريقنا وحصل على 96%. ممتاز لمشروع شركة سماء الرياض.",
    matchedEmployerIds: ["EMP-2026-001"],
  },
  {
    id: "CAND-102",
    fullName: "أ. ريم سليمان العتيبي",
    email: "reem.otaibi.growth@gmail.com",
    phone: "+966 55 876 5432",
    city: "جدة",
    country: "المملكة العربية السعودية",
    category: "marketing_sales",
    currentTitle: "Head of Growth & Performance Marketing",
    targetTitle: "VP of Growth / Senior Performance Lead",
    yearsOfExperience: 7,
    experienceLevel: "senior",
    education: "ماجستير تسويق رقمي - جامعة ولاية نيويورك | بكالوريوس إدارة أعمال - جامعة الملك عبدالعزيز",
    currentCompany: "منصة نمو للتجارة",
    noticePeriod: "immediate",
    expectedSalary: 28000,
    currentSalary: 23000,
    currency: "SAR",
    skills: ["Performance Marketing", "SEO Strategy", "Google Ads", "TikTok Ads", "GA4", "CRO", "Data Analytics", "Meta Ads", "CRM Automation"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (ممتاز)"],
    summary: "خبيرة نمو وتسويق أداء أدارت ميزانيات إعلانية تتجاوز 40 مليون ريال بنسب عائد تتجاوز 5.8x. متخصصة في توسيع تطبيقات ومنصات التجارة الإلكترونية وقيادة فرق التسويق المبني على البيانات.",
    resumeFileName: "Resume_Reem_Otaibi_Growth.pdf",
    resumeFileSize: "2.1 MB",
    portfolioUrl: "https://reemgrowth.com",
    linkedinUrl: "https://linkedin.com/in/reem-otaibi",
    status: "placed",
    rating: 5,
    submittedAt: "2026-08-01T09:00:00.000Z",
    updatedAt: "2026-08-10T11:00:00.000Z",
    hrNotes: "تم تعيينها لدى منصة نون للنمو بنجاح. أداء رائع وانطباع مبهر.",
    matchedEmployerIds: ["EMP-2026-005"],
  },
  {
    id: "CAND-103",
    fullName: "م. أحمد مصطفى الشناوي",
    email: "ahmed.shennawy.tech@gmail.com",
    phone: "+20 10 1234 5678",
    city: "القاهرة / الرياض",
    country: "مصر (جاهز للانتقال للرياض)",
    category: "technology",
    currentTitle: "Senior Full Stack Tech Lead",
    targetTitle: "Principal Software Engineer / Engineering Manager",
    yearsOfExperience: 8,
    experienceLevel: "lead",
    education: "بكالوريوس هندسة حاسبات ونظم تحكم - جامعة القاهرة",
    currentCompany: "Fintech Global Inc.",
    noticePeriod: "15_days",
    expectedSalary: 26000,
    currentSalary: 19000,
    currency: "SAR",
    skills: ["React", "Next.js", "Node.js", "TypeScript", "PostgreSQL", "System Design", "Microservices", "GraphQL", "Redis", "Docker"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (طلاقة كاملة)"],
    summary: "مهندس برمجيات رائد بنى أنظمة دفع ومعالجة معاملات مالية فورية تخدم ملايين المستخدمين. خبير في Next.js، Node.js، وقواعد البيانات الموزعة وإدارة فرق التطوير الرشيقة Agile.",
    resumeFileName: "CV_Ahmed_Shennawy_FullStack.pdf",
    resumeFileSize: "950 KB",
    portfolioUrl: "https://shennawy.dev",
    linkedinUrl: "https://linkedin.com/in/ahmed-shennawy",
    githubUrl: "https://github.com/shennawy",
    status: "available",
    rating: 5,
    submittedAt: "2026-08-14T18:00:00.000Z",
    updatedAt: "2026-08-14T18:00:00.000Z",
    hrNotes: "مرشح سوبر ستار في هندسة البرمجيات وتصميم المنظومات، جاهز للتأشيرة الفورية أو العمل عن بعد.",
    matchedEmployerIds: [],
  },
  {
    id: "CAND-104",
    fullName: "أ. ماجد فيصل الشمري (CAMS)",
    email: "m.alshammari.risk@outlook.com",
    phone: "+966 50 223 9944",
    city: "الرياض",
    country: "المملكة العربية السعودية",
    category: "finance_banking",
    currentTitle: "Senior Risk & Compliance Manager",
    targetTitle: "Head of Risk & Compliance / Chief Risk Officer",
    yearsOfExperience: 11,
    experienceLevel: "executive",
    education: "ماجستير العلوم المالية والمصرفية - جامعة الملك سعود | CAMS, FRM Certified",
    currentCompany: "بنك تجاري سعودي رائد",
    noticePeriod: "1_month",
    expectedSalary: 52000,
    currentSalary: 44000,
    currency: "SAR",
    skills: ["SAMA Regulations", "Risk Management", "CMA Compliance", "AML", "Financial Audit", "Corporate Governance", "Basel III", "Operational Risk"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (ممتاز)"],
    summary: "خبير رقابة مالية ومخاطر مصرفية بخبرة 11 عاماً في المؤسسات المالية المرخصة من ساما وهيئة السوق المالية. قاد مشاريع تدقيق ومواءمة شاملة مع لوائح بازل 3 ومكافحة غسيل الأموال.",
    resumeFileName: "Majed_Alshammari_Executive_CV.pdf",
    resumeFileSize: "1.8 MB",
    linkedinUrl: "https://linkedin.com/in/majed-alshammari-risk",
    status: "under_review",
    rating: 5,
    submittedAt: "2026-08-13T10:15:00.000Z",
    updatedAt: "2026-08-14T12:00:00.000Z",
    hrNotes: "تطابق بنسبة 98% مع طلب مجموعة الرواد المالية. تم ترتيب المقابلة مع مجلس الإدارة.",
    matchedEmployerIds: ["EMP-2026-002"],
  },
  {
    id: "CAND-105",
    fullName: "د. حسام الدين عبدالحميد (MD, MHA)",
    email: "dr.hossam.operations@gmail.com",
    phone: "+971 52 334 5566",
    city: "دبي",
    country: "الإمارات العربية المتحدة",
    category: "healthcare",
    currentTitle: "Executive Medical Director",
    targetTitle: "Chief Operating Officer - Healthcare / Medical Operations Director",
    yearsOfExperience: 14,
    experienceLevel: "executive",
    education: "دكتوراه في الطب والجراحة | ماجستير إدارة المستشفيات (MHA) - جامعة جونز هوبكنز",
    currentCompany: "المستشفى الدولي التخصصي",
    noticePeriod: "2_months",
    expectedSalary: 62000,
    currentSalary: 54000,
    currency: "SAR",
    skills: ["Hospital Administration", "JCI Standards", "Healthcare Quality", "Clinical Operations", "Budgeting", "Leadership", "Six Sigma Healthcare"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (طلاقة احترافية)", "الفرنسية (متوسط)"],
    summary: "طبيب واستشاري إدارة رعاية صحية قاد بنجاح حصول 4 مستشفيات كبرى على اعتماد JCI الدولي. متخصص في ترشيد التكاليف الطبية وتحسين كفاءة التشغيل السريري ورضا المرضى.",
    resumeFileName: "Dr_Hossam_Executive_Profile.pdf",
    resumeFileSize: "2.8 MB",
    linkedinUrl: "https://linkedin.com/in/dr-hossam-mha",
    status: "interviewed",
    rating: 5,
    submittedAt: "2026-08-07T16:00:00.000Z",
    updatedAt: "2026-08-13T14:30:00.000Z",
    hrNotes: "أجرى مقابلة ممتازة مع هيلث كير الخليج الدولية، بانتظار العرض النهائي.",
    matchedEmployerIds: ["EMP-2026-004"],
  },
  {
    id: "CAND-106",
    fullName: "أ. عمر خالد الغامدي",
    email: "omar.ghamdi.logistics@outlook.com",
    phone: "+966 54 112 8899",
    city: "الدمام",
    country: "المملكة العربية السعودية",
    category: "operations_logistics",
    currentTitle: "Operations & Fleet Supervisor",
    targetTitle: "Supply Chain & Fleet Optimization Manager",
    yearsOfExperience: 6,
    experienceLevel: "mid",
    education: "بكالوريوس إدارة سلاسل الإمداد واللوجستيات - جامعة الملك فهد",
    currentCompany: "شركة الشرق للشحن السريع",
    noticePeriod: "1_month",
    expectedSalary: 21000,
    currentSalary: 16000,
    currency: "SAR",
    skills: ["Supply Chain", "TMS", "WMS", "Fleet Management", "Inventory Control", "KPI Dashboarding", "Lean Six Sigma", "ERP Systems"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (جيد جداً)"],
    summary: "مسؤول عمليات لوجستية قاد أسطول نقل يتجاوز 180 شاحنة ومستودعات مركزية بالمنطقة الشرقية. نجح في خفض تكاليف الوقود والصيانة بنسبة 18% وتحسين دقة التسليم إلى 99.2%.",
    resumeFileName: "CV_Omar_Ghamdi_Logistics.pdf",
    resumeFileSize: "1.1 MB",
    linkedinUrl: "https://linkedin.com/in/omar-ghamdi-supplychain",
    status: "available",
    rating: 4,
    submittedAt: "2026-08-11T12:00:00.000Z",
    updatedAt: "2026-08-11T12:00:00.000Z",
    hrNotes: "شخصية ديناميكية وخبرة ميدانية ممتازة.",
    matchedEmployerIds: ["EMP-2026-006"],
  },
  {
    id: "CAND-107",
    fullName: "م. طارق يوسف حسان",
    email: "tareq.yousef.infra@gmail.com",
    phone: "+966 56 778 9900",
    city: "الرياض",
    country: "المملكة العربية السعودية",
    category: "technology",
    currentTitle: "Senior DevOps & Infrastructure Engineer",
    targetTitle: "Cloud Solutions Architect / DevOps Lead",
    yearsOfExperience: 7,
    experienceLevel: "senior",
    education: "بكالوريوس علوم الحاسب - الجامعة الأردنية",
    currentCompany: "سحابة الخليج للأنظمة",
    noticePeriod: "1_month",
    expectedSalary: 34000,
    currentSalary: 27000,
    currency: "SAR",
    skills: ["AWS", "Kubernetes", "Terraform", "Microservices", "DevOps", "Python", "CI/CD", "Helm", "Prometheus", "Ansible"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (ممتاز)"],
    summary: "مهندس بنية سحابية متمرس في بيئات Kubernetes و Terraform و CI/CD Pipelines المؤتمتة بالكامل. يمتلك خبرة عميقة في تحسين تكاليف السحابة بنسب تتجاوز 30%.",
    resumeFileName: "Tareq_Yousef_Resume.pdf",
    resumeFileSize: "1.3 MB",
    githubUrl: "https://github.com/tareq-infra",
    linkedinUrl: "https://linkedin.com/in/tareq-yousef",
    status: "shortlisted",
    rating: 4,
    submittedAt: "2026-08-12T15:30:00.000Z",
    updatedAt: "2026-08-14T11:00:00.000Z",
    hrNotes: "تم ترشيحه لشركة سماء الرياض كخيار بديل قوي.",
    matchedEmployerIds: ["EMP-2026-001"],
  },
  {
    id: "CAND-108",
    fullName: "أ. سارة إبراهيم الدوسري",
    email: "sarah.aldossary.hr@gmail.com",
    phone: "+966 50 334 1122",
    city: "الرياض",
    country: "المملكة العربية السعودية",
    category: "hr_admin",
    currentTitle: "Senior Talent Acquisition & People Partner",
    targetTitle: "HR Director / Head of People & Culture",
    yearsOfExperience: 8,
    experienceLevel: "senior",
    education: "ماجستير إدارة الموارد البشرية - جامعة مانشستر | SHRM-SCP Certified",
    currentCompany: "مجموعة استثمارية قابضة",
    noticePeriod: "1_month",
    expectedSalary: 32000,
    currentSalary: 25000,
    currency: "SAR",
    skills: ["Talent Acquisition", "HR Strategy", "SHRM", "Saudi Labor Law", "Performance Management", "Employee Engagement", "GOSI / Qiwa", "Workday"],
    languages: ["العربية (اللغة الأم)", "الإنجليزية (طلاقة كاملة)"],
    summary: "شريكة استراتيجية للموارد البشرية معتمدة من SHRM بخبرة 8 سنوات في قيادة عمليات التوظيف وتطوير الهياكل التنظيمية وتطبيق نظام العمل السعودي ونطاقات وقوى.",
    resumeFileName: "Sarah_AlDossary_HR_Profile.pdf",
    resumeFileSize: "1.6 MB",
    linkedinUrl: "https://linkedin.com/in/sarah-aldossary-hr",
    status: "available",
    rating: 5,
    submittedAt: "2026-08-13T17:00:00.000Z",
    updatedAt: "2026-08-13T17:00:00.000Z",
    hrNotes: "إمكانيات قيادية استثنائية وخبرة واسعة بنظام العمل السعودي وبوابات قوى ومقيم.",
    matchedEmployerIds: [],
  }
];

export const initialNotifications: NotificationItem[] = [
  {
    id: "NOTIF-001",
    title: "طلب توظيف جديد من شركة سماء الرياض",
    titleEn: "New Job Order from Sama Digital",
    message: "تم تسجيل طلب وظيفي عاجل لشغل منصب Lead Cloud Solutions Architect",
    messageEn: "Urgent job request registered for Lead Cloud Solutions Architect",
    type: "employer_request",
    createdAt: "2026-08-15T09:30:00.000Z",
    read: false,
    link: "/admin/employers",
  },
  {
    id: "NOTIF-002",
    title: "مرشح جديد انضم لقاعدة الكفاءات",
    titleEn: "New Candidate Registered in Talent Pool",
    message: "انضم م. محمد القحطاني (Cloud Architect) إلى قاعدة البيانات",
    messageEn: "Eng. Mohamed Al-Qahtani (Cloud Architect) joined talent pool",
    type: "candidate_applied",
    createdAt: "2026-08-15T11:00:00.000Z",
    read: false,
    link: "/admin/candidates",
  },
  {
    id: "NOTIF-003",
    title: "تم توظيف مرشح بنجاح! 🎉",
    titleEn: "Candidate Successfully Placed! 🎉",
    message: "تم إتمام توظيف أ. ريم العتيبي لدى شركة نون للنمو",
    messageEn: "Reem Al-Otaibi successfully placed at Noon Scale Lab",
    type: "status_change",
    createdAt: "2026-08-14T16:00:00.000Z",
    read: true,
    link: "/admin/employers",
  }
];
